# The cells of `checks.staged-commit-hook` (`staged-commit-hook.nix`). Deterministic: no inotify and
# no timing — the hooks THEMSELVES observe and write the checkout inside the commit's own window.
# Env: HOOK and INSTALL (the shipped `stagedCommitHook` outputs), CONFIG (the config the hook bakes).
# Prints one PASS/FAIL line per cell; the caller holds the count.
set -uo pipefail
work=$(mktemp -d)
export HOME=$work/home PRE_COMMIT_HOME=$work/pc-cache GIT_CONFIG_NOSYSTEM=1
mkdir -p "$HOME" "$work/bin" "$work/tmp"
git config --global user.email o@x
git config --global user.name o
git config --global init.defaultBranch main
bash=$(command -v bash)
fail=0
cell() { if [ "$2" = "$3" ]; then echo "PASS $1"; else echo "FAIL $1: got [$2] want [$3]"; fail=1; fi; }

# nix-store is the daemon's; the sandbox has none. The stub records what the writer asked it to root.
printf '#!%s\nprintf "%%s\\n" "$*" >> %s/nix-store.args\n' "$bash" "$work" > "$work/bin/nix-store"
chmod +x "$work/bin/nix-store"
export PATH=$work/bin:$PATH

repo=$work/repo
mkdir -p "$repo"
cd "$repo" || exit 1
git init -q
export ORACLE_REPO=$repo ORACLE_WORK=$work
printf 'base\n' | tee u.txt w.txt c.txt > /dev/null
# The declared chained command: tracked, run in the real checkout before the export.
printf '#!%s\nif [ -e "$ORACLE_WORK/chain-refuse" ]; then echo CHAIN-REFUSED; exit 1; fi\n' "$bash" > chain.sh
chmod +x chain.sh
git add u.txt w.txt c.txt chain.sh
git commit -qm base --no-verify
common=$(git rev-parse --path-format=absolute --git-common-dir)

# ── the writer, over what the old installer left: pre-commit's shim, the provisioner, hooksPath ──
printf '#!%s\n# File generated by pre-commit: https://pre-commit.com\nexit 1\n' "$bash" > .git/hooks/pre-commit
printf '#!%s\n# gen-harness: materialises a linked worktree'"'"'s pre-commit config on checkout.\nexit 1\n' "$bash" > .git/hooks/post-checkout
chmod +x .git/hooks/pre-commit .git/hooks/post-checkout
git config core.hooksPath .git/hooks
"$INSTALL" > "$work/install.log" 2>&1
cmp -s "$HOOK" .git/hooks/pre-commit && r=same || r=differs
cell install-replaces-stock-shim "$r" same
cell install-removes-retired-post-checkout "$([ -e .git/hooks/post-checkout ] && echo present || echo absent)" absent
cell install-removes-hooksPath "$(git config --get core.hooksPath || echo unset)" unset
cell install-gc-roots-the-hook "$(cat "$work/nix-store.args")" "--add-root $common/gen-harness-pre-commit --indirect --realise $HOOK"
ino=$(stat -c %i .git/hooks/pre-commit)
"$INSTALL" > "$work/install2.log" 2>&1
cell install-compares-before-writing "$(stat -c %i .git/hooks/pre-commit)" "$ino"

# ── the writer leaves a foreign slot, and a post-checkout it did not write, in place ──
foreign=$work/foreign
mkdir -p "$foreign"
git -C "$foreign" init -q
printf '#!/bin/sh\n# someone else'"'"'s hook\nexit 0\n' > "$foreign/.git/hooks/pre-commit"
printf '#!/bin/sh\n# someone else'"'"'s post-checkout\n' > "$foreign/.git/hooks/post-checkout"
fsha=$(cat "$foreign/.git/hooks/pre-commit" "$foreign/.git/hooks/post-checkout" | sha256sum)
(cd "$foreign" && "$INSTALL") > "$work/install3.log" 2>&1
cell install-keeps-foreign-slot "$(grep -c 'NOT installing' "$work/install3.log")" 1
cell install-keeps-foreign-post-checkout "$(cat "$foreign/.git/hooks/pre-commit" "$foreign/.git/hooks/post-checkout" | sha256sum)" "$fsha"

# ── the hook ──
# Every commit below runs under a private TMPDIR, which must be empty after it: a hook that `exec`s
# pre-commit loses its EXIT trap and leaks a whole export per commit.
export TMPDIR=$work/tmp
reset() { git reset -q --hard; printf 'base\n' > w.txt; }
: > "$work/target"
# 1. an unstaged tracked edit untouched throughout; a concurrent write survives; the commit lands
echo w.txt > "$work/target"
reset
echo good > c.txt
git add c.txt
echo unstaged >> u.txt
before=$(sha256sum u.txt | cut -c1-64)
git commit -qm one > "$work/1.log" 2>&1
rc=$?
cell no-write-in-window "$(cat "$work/in-window.sha")" "$before"
cell no-write-after "$(sha256sum u.txt | cut -c1-64)" "$before"
cell concurrent-write-survives "$(tail -1 w.txt)" late
cell commit-lands "$rc" 0
# 1b. a concurrent write to the UNSTAGED-EDITED file itself (the stash's conflict case) survives
reset
echo good1b > c.txt
git add c.txt
echo unstaged >> u.txt
echo u.txt > "$work/target"
git commit -qm oneb > "$work/1b.log" 2>&1
rc=$?
cell concurrent-write-to-edited-file-survives "$(tail -1 u.txt)" late
cell commit-lands-1b "$rc" 0
: > "$work/target"
# 2. a staged red refuses
reset
echo BAD > c.txt
git add c.txt
git commit -qm two > "$work/2.log" 2>&1
cell staged-red-refuses "$?" 1
# 3. a staged green passes with an unstaged red on the same file
reset
echo good2 > c.txt
git add c.txt
echo BAD >> c.txt
git commit -qm three > "$work/3.log" 2>&1
rc=$?
cell staged-green-unstaged-red-passes "$rc" 0
cell committed-content-is-staged "$(git show HEAD:c.txt)" good2
# 4. `git commit -- <path>` records the path's worktree bytes, not the index's: judged on those
reset
echo BAD > c.txt
git add c.txt
echo goodp > c.txt
git commit -qm pathspec -- c.txt > "$work/4.log" 2>&1
cell pathspec-judges-recorded-tree "$?" 0
# 5. `git commit -a` records the worktree: a BAD there refuses even with a good index
reset
echo gooda > c.txt
git add c.txt
echo BAD > c.txt
git commit -qam all > "$work/5.log" 2>&1
cell commit-a-judges-recorded-tree "$?" 1
# 6. the declared chained command runs, and its refusal refuses the commit
reset
echo goodc > c.txt
git add c.txt
touch "$work/chain-refuse"
git commit -qm chain > "$work/6.log" 2>&1
rc=$?
rm -f "$work/chain-refuse"
cell chained-command-refuses "$rc:$(grep -c CHAIN-REFUSED "$work/6.log")" 1:1
# 7. a linked worktree is gated by the common-dir slot, with nothing materialised in it
reset
git worktree add -q --detach "$work/wt" HEAD
cd "$work/wt" || exit 1
echo unstaged-wt >> u.txt
wbefore=$(sha256sum u.txt | cut -c1-64)
echo BAD > c.txt
git add c.txt
git commit -qm wt-red > "$work/7.log" 2>&1
cell worktree-staged-red-refuses "$?" 1
echo goodwt > c.txt
git add c.txt
git commit -qm wt-green > "$work/7b.log" 2>&1
rc=$?
cell worktree-staged-green-lands "$rc:$(sha256sum u.txt | cut -c1-64)" "0:$wbefore"
cd "$repo" || exit 1
cell no-export-leaked "$(find "$TMPDIR" -mindepth 1 -maxdepth 1 | wc -l)" 0
if [ "$fail" != 0 ]; then
  for f in "$work"/*.log; do echo "── $f"; cat "$f"; done
fi
exit $fail
